//後で追加する各テキストの演出データ初期値
var add_prop={
  "effect":{
    "stop":false,
    "se":"",
    "character_animation":{
      "character_first":null,
      "character_center":null,
      "character_second":null
    }
  },
  "character_position":{
    "character_first":"img/transparent_background.png",
    "character_center":"img/transparent_background.png",
    "character_second":"img/transparent_background.png"
  },
  "background_image":{
    "image":"sougen"
  }
};

var add_prop_changed={
  "A1":[
    {
      "index":0,
      "type":"character_position",
      "value":{
        "character_first":"character_img/guildtyo.png",
        "character_center":"img/test_character_02.png",
        "character_second":"character_img/gorotsuki.png"
      }
    },
    {
      "index":0,
      "type":"effect",
      "value":{
        "stop":false,
        "se":"",
        "character_animation":{
          "character_first":"purun",
          "character_center":"korokoro",
          "character_second":"poyon"
        }
      }
    },
    {
      "index":1,
      "type":"effect",
      "value":{
        "stop":false,
        "se":"",
        "character_animation":{
          "character_first":"shake",
          "character_center":"korokoro",
          "character_second":"shake"
        }
      }
    },
    {
      "index":2,
      "type":"effect",
      "value":{
        "stop":false,
        "se":"",
        "character_animation":{
          "character_first":"purupuru",
          "character_center":"poyooon",
          "character_second":"left_right"
        }
      }
    },
    {
      "index":1,
      "type":"character_position",
      "value":{
        "character_first":"character_img/guildtyo.png",
        "character_center":"img/test_character_02.png",
        "character_second":"character_img/gorotsuki.png"
      }
    },
    {
      "index":2,
      "type":"character_position",
      "value":{
        "character_first":"character_img/guildtyo.png",
        "character_center":"img/test_character_02.png",
        "character_second":"character_img/gorotsuki.png"
      }
    },
    {
      "index":3,
      "type":"character_position",
      "value":{
        "character_first":"img/transparent_background.png",
        "character_center":"img/test_character_02.png",
        "character_second":"img/transparent_background.png"
      }
    },
    {
      "index":4,
      "type":"character_position",
      "value":{
        "character_first":"img/transparent_background.png",
        "character_center":"img/test_character_02.png",
        "character_second":"img/test_character_02.png"
      }
    },
    {
      "index":5,
      "type":"character_position",
      "value":{
        "character_first":"img/transparent_background.png",
        "character_center":"img/transparent_background.png",
        "character_second":"img/test_character_02.png"
      }
    },
  ],
  "A7":[{
    "index":4,
    "type":"effect",
    "value":{
      "stop":true,
      "se":"audio/door.m4a"
    }
  },
  {
    "index":4,
    "type":"character_position",
    "value":{
      "character_first":"img/guildtyo_w.jpg",
      "character_center":"img/transparent_background.png",
      "character_second":"img/gorotsuki_w.jpg"
    }    
  }
  ],
  "A8":[{
    "index":5,
    "type":"effect",
    "value":{
      "stop":true,
      "se":""
    }
  }],
  "A28":[
    {
      "index":0,
      "type":"effect",
      "value":{
        "stop":true,
        "se":"",
        "flash":true
      }
    },
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":0,
      "type":"character_position",
      "value":{
        "character_first":"img/transparent_background.png",
        "character_center":"img/transparent_background.png",
        "character_second":"img/transparent_background.png"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":13,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":14,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":15,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":16,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":17,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":18,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":19,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":20,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    }
  ],
  "A29":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"kaidan"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"kaidan"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"kaidan"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"kaidan"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    }
  ],
  "A30":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"waterflow"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":13,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":14,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":15,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":16,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":17,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    }
  ],
  "A31":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"waterflow"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":13,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":14,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":15,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":16,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":17,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    }
  ]
}