//後で追加する各テキストの演出データ初期値
var add_prop={
  "effect":{
    "stop":false,
    "se":"",
    "character_animation":{
      "character_first":null,
      "character_center":null,
      "character_second":null
    }
  },
  "character_position":{
    "character_first":"img/transparent_background.png",
    "character_center":"img/transparent_background.png",
    "character_second":"img/transparent_background.png"
  },
  "background_image":{
    "image":"sougen"
  }
};

var add_prop_changed={
  "A1":[
    {
      "index":0,
      "type":"character_position",
      "value":{
        "character_first":"character_img/guildtyo.png",
        "character_center":"img/test_character_02.png",
        "character_second":"character_img/gorotsuki.png"
      }
    },
    {
      "index":0,
      "type":"effect",
      "value":{
        "stop":false,
        "se":"",
        "character_animation":{
          "character_first":"purun",
          "character_center":"korokoro",
          "character_second":"poyon"
        }
      }
    },
    {
      "index":1,
      "type":"effect",
      "value":{
        "stop":false,
        "se":"",
        "character_animation":{
          "character_first":"shake",
          "character_center":"korokoro",
          "character_second":"shake"
        }
      }
    },
    {
      "index":2,
      "type":"effect",
      "value":{
        "stop":false,
        "se":"",
        "character_animation":{
          "character_first":"purupuru",
          "character_center":"poyooon",
          "character_second":"left_right"
        }
      }
    },
    {
      "index":1,
      "type":"character_position",
      "value":{
        "character_first":"character_img/king.png",
        "character_center":"character_img/minister.png",
        "character_second":"character_img/receptionist.png"
      }
    },
    {
      "index":2,
      "type":"character_position",
      "value":{
        "character_first":"character_img/guildtyo.png",
        "character_center":"img/test_character_02.png",
        "character_second":"character_img/gorotsuki.png"
      }
    },
    {
      "index":3,
      "type":"character_position",
      "value":{
        "character_first":"img/transparent_background.png",
        "character_center":"img/test_character_02.png",
        "character_second":"img/transparent_background.png"
      }
    },
    {
      "index":4,
      "type":"character_position",
      "value":{
        "character_first":"img/transparent_background.png",
        "character_center":"img/test_character_02.png",
        "character_second":"img/test_character_02.png"
      }
    },
    {
      "index":5,
      "type":"character_position",
      "value":{
        "character_first":"img/transparent_background.png",
        "character_center":"img/transparent_background.png",
        "character_second":"img/test_character_02.png"
      }
    },
  ],
  "A7":[
    {
      "index":4,
      "type":"effect",
      "value":{
          "stop":true,
          "se":""
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    }
  ],
  "A8":[
    {
      "index":5,
      "type":"effect",
      "value":{
        "stop":true,
        "se":""
      }    
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    }
  ],
  "A9":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    }
  ],
  "A10":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    }
  ],
  "A11":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"city_1"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    },
    {
      "index":13,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    },
    {
      "index":14,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    },
    {
      "index":15,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    },
    {
      "index":16,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    }
  ],
  "A12":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":13,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":14,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":15,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":16,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":17,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":18,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":19,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":20,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":21,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":22,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":23,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":24,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":25,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    }
  ],
  "A13":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    }
  ],
  "A14":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    },
    {
      "index":13,
      "type":"background_image",
      "value":{
        "image":"city_2"
      }
    }
  ],
  "A15":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":13,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":14,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":15,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":16,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    }
  ],
  "A16":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    }
  ],
  "A17":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    }
  ],
  "A18":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    }
  ],
  "A19":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"sora"
      }
    }
  ],
  "A20":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"city_3"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"city_3"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"city_3"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"city_3"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"city_3"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"city_3"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"city_3"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"city_3"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"city_3"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"city_3"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"city_3"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"city_3"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"city_3"
      }
    }
  ],
  "A21":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    }
  ],
  "A22":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    }
  ],
  "A23":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"yane"
      }
    }
  ],
  "A28":[
    {
      "index":0,
      "type":"effect",
      "value":{
        "stop":true,
        "se":"",
        "flash":true
      }
    },
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":0,
      "type":"character_position",
      "value":{
        "character_first":"img/transparent_background.png",
        "character_center":"img/transparent_background.png",
        "character_second":"img/transparent_background.png"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":13,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":14,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":15,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":16,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":17,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":18,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":19,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":20,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    }
  ],
  "A29":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"kaidan"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"kaidan"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"kaidan"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"kaidan"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    }
  ],
  "A30":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"waterflow"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":13,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":14,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":15,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":16,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":17,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    }
  ],
  "A31":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"waterflow"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"cumulonimbs"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":11,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":12,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":13,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":14,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":15,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":16,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    },
    {
      "index":17,
      "type":"background_image",
      "value":{
        "image":"nasubi"
      }
    }
  ],
  "C1A":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    },
    {
      "index":0,
      "type":"effect",
      "value":{
          "stop":true,
          "se":"audio/asioto.m4a"
      }
    }
  ],
  "C1B":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    },
    {
      "index":0,
      "type":"effect",
      "value":{
          "stop":true,
          "se":"audio/asioto.m4a"
      }
    }
  ],
  "C1C":[
    {
      "index":0,
      "type":"effect",
      "value":{
          "stop":true,
          "se":"audio/asioto.m4a"
      }
    }
  ],
  "C1D":[
    {
      "index":0,
      "type":"effect",
      "value":{
          "stop":true,
          "se":"audio/asioto.m4a"
      }
    }
  ],
  "C2D3_":[
    {
      "index":0,
      "type":"effect",
      "value":{
          "stop":true,
          "se":"audio/asioto.m4a"
      }
    }
  ],
  "C1E":[
    {
      "index":0,
      "type":"effect",
      "value":{
          "stop":true,
          "se":"audio/asioto.m4a"
      }
    }
  ],
  "C4E":[
    {
      "index":0,
      "type":"effect",
      "value":{
          "stop":true,
          "se":"audio/asioto.m4a"
      }
    }
  ],
  "C3E1":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    }
  ],
  "C3E2":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":5,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":6,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":7,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":8,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":9,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":10,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    }
  ],
  "C3E1_1":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    }
  ],
  "C3E1_2":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    }
  ],
  "C3E1_3":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    }
  ],
  "C3E1_4":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    }
  ],
  "C3E":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    },
    {
      "index":4,
      "type":"background_image",
      "value":{
        "image":"leaf_and_sky"
      }
    }
  ],
  "C1F":[
    {
      "index":0,
      "type":"effect",
      "value":{
          "stop":true,
          "se":"audio/asioto.m4a"
      }
    }
  ],
  "C4E":[
    {
      "index":0,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    },
    {
      "index":1,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    },
    {
      "index":2,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    },
    {
      "index":3,
      "type":"background_image",
      "value":{
        "image":"black"
      }
    }
  ],
  "C1G":[
    {
      "index":0,
      "type":"effect",
      "value":{
          "stop":true,
          "se":"audio/asioto.m4a"
      }
    }
  ]
}